services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: AUTO_CURSEFORGE
      EULA: "TRUE"
      MEMORY: 16G
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: uncharted-expeditions
    volumes:
      ./cf_uncharted_expeditions:/data
